// src/Footer.svelte
<script>
    export let text;
    export let i;
    export let link;
</script>

<a
  href={link}
  class="inline-block text-sm m-2 px-4 py-2 leading-none border rounded border-white text-white hover:border-transparent hover:text-teal-500 hover:bg-white transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-110"
>
  <i class={i}></i>
  {text}
</a>

// src/components/Footer.vue
<template>
  <div class="mt-6">
    <a
      href="https://youtube.com/eddiejaoude?sub_confirmation=1"
      class="inline-block text-sm m-2 px-4 py-2 leading-none border rounded border-white text-white hover:border-transparent hover:text-teal-500 hover:bg-white transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-110"
    >
      <i class="fab fa-youtube-square"></i>
      YouTube</a
    >
    <a
      href="http://github.com/EddieJaoudeCommunity"
      class="inline-block text-sm m-2 px-4 py-2 leading-none border rounded border-white text-white hover:border-transparent hover:text-teal-500 hover:bg-white transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-110"
    >
      <i class="fab fa-github-square"></i>
      GitHub</a
    >
    <a
      href="https://discord.com/invite/jZQs6Wu"
      class="inline-block text-sm m-2 px-4 py-2 leading-none border rounded border-white text-white hover:border-transparent hover:text-teal-500 hover:bg-white transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-110"
    >
      <i class="fab fa-discord"></i>
      Discord</a
    >
  </div>
</template>

<script>
export default {};
</script>

<style></style>
