// reactjs/src/components/Footer.tsx
import React from 'react';

interface Props{
    link:string,
    i:string,
    text:string
}

const Footer: React.FC<Props> = ({link, i, text}):JSX.Element => {
    return (
        
<a
  href={link}
  className="inline-block text-sm m-2 px-4 py-2 leading-none border rounded border-white text-white hover:border-transparent hover:text-teal-500 hover:bg-white transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-110"
>
  <i className={i}></i>
  {text}
</a>
    )
}

export default Footer;

// src/Footer.svelte
<script>
    export let text;
    export let i;
    export let link;
</script>

<a
  href={link}
  class="inline-block text-sm m-2 px-4 py-2 leading-none border rounded border-white text-white hover:border-transparent hover:text-teal-500 hover:bg-white transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-110"
>
  <i class={i}></i>
  {text}
</a>
